import Header from '@/components/header/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Roboto, Open_Sans } from 'next/font/google';
import Providers from '@/components/Providers';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
});
const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.variable} ${openSans.variable}`}>
      <body>
        <Providers>
          <>
            <Header />
            <main>{children}</main>
          </>
        </Providers>
      </body>
    </html>
  );
}
